const ecoPoints = [
    {
        id: 1,
        name: "Водоразборная колонка",
        address: "переулок Бестужева, 5",
        lat: 51.656831,
        lng: 39.195471,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 2,
        name: "Водоразборная колонка",
        address: "улица Лётчика Щербакова, 31",
        lat: 51.649644,
        lng: 39.181726,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 3,
        name: "Водоразборная колонка",
        address: "улица Лётчика Колесниченко, 10",
        lat: 51.644410,
        lng: 39.176946,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 4,
        name: "Водоразборная колонка",
        address: "Пеше-Стрелецкая улица, 9",
        lat: 51.666643,
        lng: 39.168999,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 5,
        name: "Водоразборная колонка",
        address: "Енисеевская улица, 1",
        lat: 51.643761,
        lng: 39.210344,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 6,
        name: "Водоразборная колонка",
        address: "Бауманский переулок, 19",
        lat: 51.655663,
        lng: 39.209964,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 7,
        name: "Водоразборная колонка",
        address: "Мало-Красноармейская улица, 28",
        lat: 51.642966,
        lng: 39.184669,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 8,
        name: "Водоразборная колонка",
        address: "Сиреневая улица, 10",
        lat: 51.659350,
        lng: 39.213275,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 9,
        name: "Водоразборная колонка",
        address: "улица Гаршина, 6",
        lat: 51.679146,
        lng: 39.249407,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 10,
        name: "Водоразборная колонка",
        address: "улица Транспортная, 15",
        lat: 51.685518,
        lng: 39.211664,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 11,
        name: "Водоразборная колонка",
        address: "улица Транспортная, 33",
        lat: 51.687409,
        lng: 39.209771,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 12,
        name: "Водоразборная колонка",
        address: "улица Декабристов, 8",
        lat: 51.657652,
        lng: 39.213060,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 13,
        name: "Водоразборная колонка",
        address: "Планерный переулок, 5",
        lat: 51.649369,
        lng: 39.235682,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 14,
        name: "Водоразборная колонка",
        address: "улица 45-й Стрелковой Дивизии, 82",
        lat: 51.695895,
        lng: 39.193472,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 15,
        name: "Водоразборная колонка",
        address: "улица Пятницкого, 21",
        lat: 51.667617,
        lng: 39.217707,
        type: "water",
        waterSubtype: "kolonka",
        district: "Центральный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 16,
        name: "Водоразборная колонка",
        address: "улица Пятницкого, 53",
        lat: 51.667801,
        lng: 39.211939,
        type: "water",
        waterSubtype: "kolonka",
        district: "Центральный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 17,
        name: "Водоразборная колонка",
        address: "улица Коперника, 34/2",
        lat: 51.651171,
        lng: 39.200788,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 18,
        name: "Водоразборная колонка",
        address: "улица Лётчика Щербакова, 8А",
        lat: 51.652148,
        lng: 39.183862,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 19,
        name: "Водоразборная колонка",
        address: "улица Бехтерева, 12",
        lat: 51.662255,
        lng: 39.215994,
        type: "water",
        waterSubtype: "kolonka",
        district: "Центральный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 20,
        name: "Водоразборная колонка",
        address: "улица Челюскинцев, 133",
        lat: 51.651424,
        lng: 39.189780,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 21,
        name: "Водоразборная колонка",
        address: "переулок Нансена, 6",
        lat: 51.651332,
        lng: 39.188243,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 22,
        name: "Водоразборная колонка",
        address: "улица Новикова, 37",
        lat: 51.616650,
        lng: 39.233286,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 23,
        name: "Водоразборная колонка",
        address: "Кавалерийская улица, 35",
        lat: 51.685739,
        lng: 39.225009,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 24,
        name: "Водоразборная колонка",
        address: "улица Героев Революции, 55Б",
        lat: 51.691360,
        lng: 39.228232,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 25,
        name: "Водоразборная колонка",
        address: "улица Героев Революции, 90",
        lat: 51.690701,
        lng: 39.230952,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 26,
        name: "Водоразборная колонка",
        address: "Приветливый переулок, 2",
        lat: 51.684619,
        lng: 39.206939,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 27,
        name: "Водоразборная колонка",
        address: "Краснознамённая улица, 45",
        lat: 51.649192,
        lng: 39.185683,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 28,
        name: "Водоразборная колонка",
        address: "улица Туполева, 21",
        lat: 51.637957,
        lng: 39.271524,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 29,
        name: "Водоразборная колонка",
        address: "Мичуринская улица, 441",
        lat: 51.585269,
        lng: 39.159326,
        type: "water",
        waterSubtype: "kolonka",
        district: "Советский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 30,
        name: "Водоразборная колонка",
        address: "улица 17 Сентября, 38",
        lat: 51.661708,
        lng: 39.275494,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 31,
        name: "Водоразборная колонка",
        address: "Московский проспект, 127",
        lat: 51.716495,
        lng: 39.176461,
        type: "water",
        waterSubtype: "kolonka",
        district: "Коминтерновский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 32,
        name: "Водоразборная колонка",
        address: "Полтавский переулок, 28",
        lat: 51.673617,
        lng: 39.260047,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 33,
        name: "Водоразборная колонка",
        address: "Волгоградская улица, 25",
        lat: 51.657770,
        lng: 39.275731,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 34,
        name: "Водоразборная колонка",
        address: "Ангарский переулок, 7",
        lat: 51.635271,
        lng: 39.204999,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 35,
        name: "Водоразборная колонка",
        address: "Большая Чернавская улица, 20А",
        lat: 51.670190,
        lng: 39.214979,
        type: "water",
        waterSubtype: "kolonka",
        district: "Центральный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 36,
        name: "Водоразборная колонка",
        address: "улица Ленина, 66А",
        lat: 51.688364,
        lng: 39.219145,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 37,
        name: "Водоразборная колонка",
        address: "улица Ленина, 42",
        lat: 51.689890,
        lng: 39.221755,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 38,
        name: "Водоразборная колонка",
        address: "улица Сакко и Ванцетти, 50",
        lat: 51.681834,
        lng: 39.220889,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 39,
        name: "Водоразборная колонка",
        address: "Спортивная набережная, 13Т",
        lat: 51.671331,
        lng: 39.246005,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 40,
        name: "Водоразборная колонка",
        address: "Кабельный переулок, 11",
        lat: 51.664546,
        lng: 39.178820,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 41,
        name: "Водоразборная колонка",
        address: "улица Красных Зорь, 3",
        lat: 51.671787,
        lng: 39.162395,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 42,
        name: "Водоразборная колонка",
        address: "улица Победы, 16",
        lat: 51.694032,
        lng: 39.189002,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 43,
        name: "Водоразборная колонка",
        address: "улица Чернышевский Бугор, 1",
        lat: 51.645011,
        lng: 39.210007,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 44,
        name: "Водоразборная колонка",
        address: "Смоленская улица, 39",
        lat: 51.680200,
        lng: 39.217412,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 45,
        name: "Водоразборная колонка",
        address: "улица Ильича, 15",
        lat: 51.677820,
        lng: 39.246460,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 46,
        name: "Водоразборная колонка",
        address: "улица Ильича, 32",
        lat: 51.676115,
        lng: 39.246308,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 47,
        name: "Водоразборная колонка",
        address: "улица Коммунистической Молодёжи, 11",
        lat: 51.687265,
        lng: 39.228325,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 48,
        name: "Водоразборная колонка",
        address: "улица Демократии, 5А",
        lat: 51.681740,
        lng: 39.226506,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 49,
        name: "Водоразборная колонка",
        address: "улица Демократии, 42",
        lat: 51.682637,
        lng: 39.222844,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 50,
        name: "Водоразборная колонка",
        address: "Полевая улица, 11",
        lat: 51.689621,
        lng: 39.211830,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 51,
        name: "Водоразборная колонка",
        address: "улица Бархатный Бугор, 23",
        lat: 51.651296,
        lng: 39.205034,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 52,
        name: "Водоразборная колонка",
        address: "Батуринская улица, 15Б",
        lat: 51.675770,
        lng: 39.222588,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 53,
        name: "Водоразборная колонка",
        address: "Кавалерийская улица, 47",
        lat: 51.685854,
        lng: 39.223404,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 54,
        name: "Водоразборная колонка",
        address: "улица Пролетарской Диктатуры, 7",
        lat: 51.687092,
        lng: 39.226703,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 55,
        name: "Водоразборная колонка",
        address: "проспект Патриотов, 11/3",
        lat: 51.638625,
        lng: 39.128630,
        type: "water",
        waterSubtype: "kolonka",
        district: "Советский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 56,
        name: "Водоразборная колонка",
        address: "переулок Парашютистов, 4",
        lat: 51.649229,
        lng: 39.236364,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 57,
        name: "Водоразборная колонка",
        address: "Клубная улица, 43",
        lat: 51.647349,
        lng: 39.202364,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 58,
        name: "Водоразборная колонка",
        address: "Штурмовой переулок, 1",
        lat: 51.647786,
        lng: 39.182998,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 59,
        name: "Водоразборная колонка",
        address: "улица Урицкого, 15",
        lat: 51.682581,
        lng: 39.211957,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 60,
        name: "Водоразборная колонка",
        address: "улица Хользунова, 12",
        lat: 51.703259,
        lng: 39.193395,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 61,
        name: "Техническая вода",
        address: "улица Димитрова, 149Б",
        lat: 51.662206,
        lng: 39.290651,
        type: "water",
        waterSubtype: "tech",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Техническая вода",
        recyclingTypes: []
    },
    {
        id: 62,
        name: "Водоразборная колонка",
        address: "улица Веры Фигнер, 55",
        lat: 51.644968,
        lng: 39.204884,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 63,
        name: "Водоразборная колонка",
        address: "улица Дурова, 6",
        lat: 51.677871,
        lng: 39.224590,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 64,
        name: "Водоразборная колонка",
        address: "улица Эртеля, 14",
        lat: 51.669118,
        lng: 39.217762,
        type: "water",
        waterSubtype: "kolonka",
        district: "Центральный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 65,
        name: "Водоразборная колонка",
        address: "улица Филатова, 3",
        lat: 51.679689,
        lng: 39.245058,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 66,
        name: "Водоразборная колонка",
        address: "улица Филатова, 13",
        lat: 51.679489,
        lng: 39.246733,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 67,
        name: "Водоразборная колонка",
        address: "Фронтовая улица, 34",
        lat: 51.697481,
        lng: 39.233944,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 68,
        name: "Водоразборная колонка",
        address: "улица Войкова, 50",
        lat: 51.669647,
        lng: 39.184566,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 69,
        name: "Водоразборная колонка",
        address: "улица Кубанская Гора, 9",
        lat: 51.639282,
        lng: 39.207779,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 70,
        name: "Водоразборная колонка",
        address: "Подклетенская улица, 92",
        lat: 51.681761,
        lng: 39.159396,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 71,
        name: "Водоразборная колонка",
        address: "Комсомольская улица, 7/2",
        lat: 51.678684,
        lng: 39.245322,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 72,
        name: "Водоразборная колонка",
        address: "Комсомольская улица, 27А",
        lat: 51.678159,
        lng: 39.248487,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 73,
        name: "Водоразборная колонка",
        address: "улица Чернышевский Бугор, 22",
        lat: 51.645075,
        lng: 39.206757,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 74,
        name: "Водоразборная колонка",
        address: "улица Обороны Революции, 58",
        lat: 51.688362,
        lng: 39.229590,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 75,
        name: "Водоразборная колонка",
        address: "Трудовая улица, 17",
        lat: 51.682557,
        lng: 39.226316,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 76,
        name: "Водоразборная колонка",
        address: "Пролетарская улица, 6",
        lat: 51.679631,
        lng: 39.225321,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 77,
        name: "Водоразборная колонка",
        address: "Мало-Смоленская улица, 37",
        lat: 51.680731,
        lng: 39.220702,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 78,
        name: "Водоразборная колонка",
        address: "улица Маршала Жукова, 26",
        lat: 51.716494,
        lng: 39.176488,
        type: "water",
        waterSubtype: "kolonka",
        district: "Коминтерновский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 79,
        name: "Водоразборная колонка",
        address: "территория гаражно-строительного кооператива Орбита, 148",
        lat: 51.683504,
        lng: 39.133943,
        type: "water",
        waterSubtype: "kolonka",
        district: "Советский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 80,
        name: "Водоразборная колонка",
        address: "Социалистическая улица, 5",
        lat: 51.683294,
        lng: 39.209238,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 81,
        name: "Водоразборная колонка",
        address: "Целинная улица, 18",
        lat: 51.682367,
        lng: 39.217990,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 82,
        name: "Водоразборная колонка",
        address: "Учительский переулок, 15",
        lat: 51.685789,
        lng: 39.220064,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 83,
        name: "Водоразборная колонка",
        address: "Крутая улица, 17",
        lat: 51.680836,
        lng: 39.217032,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 84,
        name: "Водоразборная колонка",
        address: "улица Красной Работницы, 3",
        lat: 51.689511,
        lng: 39.222408,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 85,
        name: "Водоразборная колонка",
        address: "улица Гастелло, 6",
        lat: 51.709260,
        lng: 39.232479,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 86,
        name: "Водоразборная колонка",
        address: "Беговая улица, 53",
        lat: 51.697410,
        lng: 39.185967,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 87,
        name: "Водоразборная колонка",
        address: "улица Казакова, 33",
        lat: 51.710338,
        lng: 39.239436,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 88,
        name: "Водоразборная колонка",
        address: "улица Рокоссовского, 24А",
        lat: 51.703590,
        lng: 39.271057,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 89,
        name: "Водоразборная колонка",
        address: "Тракторная улица, 53",
        lat: 51.697664,
        lng: 39.260190,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 90,
        name: "Водоразборная колонка",
        address: "улица Тургенева, 12/2",
        lat: 51.728012,
        lng: 39.258774,
        type: "water",
        waterSubtype: "kolonka",
        district: "Коминтерновский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 91,
        name: "Водоразборная колонка",
        address: "улица Артёма, 19",
        lat: 51.729292,
        lng: 39.263316,
        type: "water",
        waterSubtype: "kolonka",
        district: "Коминтерновский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 92,
        name: "Водоразборная колонка",
        address: "Паровозная улица, 13А",
        lat: 51.732155,
        lng: 39.263372,
        type: "water",
        waterSubtype: "kolonka",
        district: "Коминтерновский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 93,
        name: "Водоразборная колонка",
        address: "Богучарская улица, 49",
        lat: 51.737046,
        lng: 39.273668,
        type: "water",
        waterSubtype: "kolonka",
        district: "Коминтерновский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 94,
        name: "Водоразборная колонка",
        address: "Калининградская улица, 62",
        lat: 51.739118,
        lng: 39.276789,
        type: "water",
        waterSubtype: "kolonka",
        district: "Коминтерновский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 95,
        name: "Водоразборная колонка",
        address: "Калининградская улица, 139",
        lat: 51.738496,
        lng: 39.292463,
        type: "water",
        waterSubtype: "kolonka",
        district: "Коминтерновский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 96,
        name: "Водоразборная колонка",
        address: "Набережная улица, 5",
        lat: 51.675813,
        lng: 39.244333,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 97,
        name: "Водоразборная колонка",
        address: "Набережная улица, 10",
        lat: 51.677018,
        lng: 39.244472,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 98,
        name: "Водоразборная колонка",
        address: "Международный переулок, 37",
        lat: 51.667102,
        lng: 39.260499,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 99,
        name: "Водоразборная колонка",
        address: "Гражданский переулок, 25",
        lat: 51.666134,
        lng: 39.257131,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 100,
        name: "Водоразборная колонка",
        address: "Улица Огарёва, 24",
        lat: 51.665606,
        lng: 39.258562,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 101,
        name: "Водоразборная колонка",
        address: "Международный переулок, 23",
        lat: 51.665479,
        lng: 39.259733,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 102,
        name: "Водоразборная колонка",
        address: "Нахимовская улица, 8",
        lat: 51.667751,
        lng: 39.265827,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 103,
        name: "Водоразборная колонка",
        address: "Переулок Крамского, 17",
        lat: 51.663960,
        lng: 39.263208,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 104,
        name: "Водоразборная колонка",
        address: "Переулок Поленова, 18",
        lat: 51.663809,
        lng: 39.264873,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 105,
        name: "Водоразборная колонка",
        address: "Переулок Бродского, 38",
        lat: 51.661397,
        lng: 39.274046,
        type: "water",
        waterSubtype: "kolonka",
        district: "Железнодорожный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 106,
        name: "Водоразборная колонка",
        address: "Улица Новикова, 71",
        lat: 51.615746,
        lng: 39.229783,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 107,
        name: "Водоразборная колонка",
        address: "Улица Новикова, 128",
        lat: 51.612996,
        lng: 39.217450,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 108,
        name: "Водоразборная колонка",
        address: "Улица Новикова, 207",
        lat: 51.610749,
        lng: 39.214245,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 109,
        name: "Водоразборная колонка",
        address: "Ленинский проспект, 170",
        lat: 51.687112,
        lng: 39.271845,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 110,
        name: "Водоразборная колонка",
        address: "Улица Рокоссовского, 14/2",
        lat: 51.703934,
        lng: 39.269306,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 111,
        name: "Водоразборная колонка",
        address: "Улица Суворова, 108",
        lat: 51.701673,
        lng: 39.268934,
        type: "water",
        waterSubtype: "kolonka",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 112,
        name: "Водоразборная колонка",
        address: "Улица Пугачёва, 11",
        lat: 51.735726,
        lng: 39.263753,
        type: "water",
        waterSubtype: "kolonka",
        district: "Коминтерновский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 113,
        name: "Водоразборная колонка",
        address: "Пионерская улица, 82",
        lat: 51.738036,
        lng: 39.269850,
        type: "water",
        waterSubtype: "kolonka",
        district: "Коминтерновский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 114,
        name: "Водоразборная колонка",
        address: "Белгородская улица, 64/2",
        lat: 51.737974,
        lng: 39.272861,
        type: "water",
        waterSubtype: "kolonka",
        district: "Коминтерновский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Водоразборная колонка",
        recyclingTypes: []
    },
    {
        id: 115,
        name: "Ключ, ручей",
        address: "городской округ Воронеж, Центральный район",
        lat: 51.742492,
        lng: 39.226337,
        type: "water",
        waterSubtype: "spring",
        district: "Центральный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Родник, ключ",
        recyclingTypes: []
    },
    {
        id: 116,
        name: "Ключ, ручей",
        address: "городской округ Воронеж, Центральный район",
        lat: 51.743604,
        lng: 39.225559,
        type: "water",
        waterSubtype: "spring",
        district: "Центральный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Родник, ключ",
        recyclingTypes: []
    },
    {
        id: 117,
        name: "Ключ, ручей",
        address: "потребительский кооператив рыболовов-любителей Маяк-1",
        lat: 51.747279,
        lng: 39.227553,
        type: "water",
        waterSubtype: "spring",
        district: "Центральный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Родник, ключ",
        recyclingTypes: []
    },
    {
        id: 118,
        name: "Ключ, ручей",
        address: "городской округ Воронеж, Центральный район",
        lat: 51.755698,
        lng: 39.226932,
        type: "water",
        waterSubtype: "spring",
        district: "Центральный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Родник, ключ",
        recyclingTypes: []
    },
    {
        id: 119,
        name: "Ключ, ручей",
        address: "городской округ Воронеж, Центральный район",
        lat: 51.753201,
        lng: 39.225003,
        type: "water",
        waterSubtype: "spring",
        district: "Центральный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Родник, ключ",
        recyclingTypes: []
    },
    {
        id: 120,
        name: "Ключ, ручей",
        address: "городской округ Воронеж, Центральный район",
        lat: 51.757589,
        lng: 39.229895,
        type: "water",
        waterSubtype: "spring",
        district: "Центральный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Родник, ключ",
        recyclingTypes: []
    },
    {
        id: 121,
        name: "Ключ, ручей 'Ржавчик'",
        address: "городской округ Воронеж, Центральный район",
        lat: 51.738430,
        lng: 39.204341,
        type: "water",
        waterSubtype: "spring",
        district: "Центральный",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Родник, ключ",
        recyclingTypes: []
    },
    {
        id: 122,
        name: "Источник святителя Тихона Амафуитского",
        address: "городской округ Воронеж, Коминтерновский район, Княжеский сквер",
        lat: 51.740294,
        lng: 39.137774,
        type: "water",
        waterSubtype: "spring",
        district: "Коминтерновский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Святой источник",
        recyclingTypes: []
    },
    {
        id: 123,
        name: "Подгоренский родник",
        address: "городской округ Воронеж, Коминтерновский район, Княжеский сквер",
        lat: 51.738171,
        lng: 39.137504,
        type: "water",
        waterSubtype: "spring",
        district: "Коминтерновский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Родник",
        recyclingTypes: []
    },
    {
        id: 124,
        name: "Родник 'Дружба'",
        address: "площадь Советов, 18",
        lat: 51.734398,
        lng: 39.136309,
        type: "water",
        waterSubtype: "spring",
        district: "Коминтерновский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Родник",
        recyclingTypes: []
    },
    {
        id: 125,
        name: "Ключ, ручей",
        address: "Воронеж, Малая роща",
        lat: 51.701051,
        lng: 39.093585,
        type: "water",
        waterSubtype: "spring",
        district: "Советский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Родник, ключ",
        recyclingTypes: []
    },
    {
        id: 126,
        name: "Ключ, ручей",
        address: "Воронеж, Советский район, микрорайон Тенистый",
        lat: 51.630740,
        lng: 39.073383,
        type: "water",
        waterSubtype: "spring",
        district: "Советский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Родник, ключ",
        recyclingTypes: []
    },
    {
        id: 127,
        name: "Ключ, ручей",
        address: "Воронеж, Советский район, микрорайон Тенистый",
        lat: 51.634671,
        lng: 39.073375,
        type: "water",
        waterSubtype: "spring",
        district: "Советский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Родник, ключ",
        recyclingTypes: []
    },
    {
        id: 128,
        name: "Ключ, ручей",
        address: "городской округ Воронеж, Советский район, Шиловский лес",
        lat: 51.606668,
        lng: 39.181125,
        type: "water",
        waterSubtype: "spring",
        district: "Советский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Родник, ключ",
        recyclingTypes: []
    },
    {
        id: 129,
        name: "Ключ, ручей",
        address: "Заозёрный переулок, 1",
        lat: 51.641416,
        lng: 39.209912,
        type: "water",
        waterSubtype: "spring",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Родник, ключ",
        recyclingTypes: []
    },
    {
        id: 130,
        name: "Источник святителя Митрофана Воронежского",
        address: "улица Софьи Перовской, 96",
        lat: 51.653377,
        lng: 39.209316,
        type: "water",
        waterSubtype: "spring",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Святой источник",
        recyclingTypes: []
    },






















        // ========== ПУНКТЫ ПРИЁМА ВТОРСЫРЬЯ (id 131–181) ==========
    {
        id: 131,
        name: "Воронежвторма (Сакко и Ванцетти)",
        address: "ул. Сакко и Ванцетти, 54в, Воронеж",
        lat: 51.681581,
        lng: 39.220418,
        type: "recycling",
        district: "Ленинский",
        hours: "Пн–Пт 08:00–17:00, Сб–Вс выходной",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, ПЭТ-бутылки, стекло",
        contacts: "+7 (4732) 21-80-70",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass"]
    },
    {
        id: 132,
        name: "Воронежвторма (Пеше-Стрелецкая)",
        address: "ул. Пеше-Стрелецкая, 159В, Воронеж",
        lat: 51.656043,
        lng: 39.141196,
        type: "recycling",
        district: "Советский",
        hours: "Пн–Пт 08:00–15:00 (перерыв 13:00–13:30), Сб 08:00–14:00",
        hoursType: "regular",
        description: "Бумага, макулатура",
        contacts: "+7 (4732) 21-80-70",
        website: "",
        recyclingTypes: ["paper"]
    },
    {
        id: 133,
        name: "Воронежвторма (Циолковского)",
        address: "ул. Циолковского, 125Б, Воронеж",
        lat: 51.633128,
        lng: 39.269233,
        type: "recycling",
        district: "Железнодорожный",
        hours: "Пн–Сб 09:00–16:00",
        hoursType: "regular",
        description: "Макулатура",
        contacts: "+7 (4732) 21-80-22",
        website: "",
        recyclingTypes: ["paper"]
    },
    {
        id: 134,
        name: "Воронежвторма (Моисеева)",
        address: "ул. Моисеева, 2 (ост. «Цирк»), Воронеж",
        lat: 51.656417,
        lng: 39.185177,
        type: "recycling",
        district: "Ленинский",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, ПЭТ, стекло",
        contacts: "+7 (4732) 21-80-70",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass"]
    },
    {
        id: 135,
        name: "Воронежвторма (Донбасская)",
        address: "ул. Донбасская, 10 (ост. «Площадь Заставы»), Воронеж",
        lat: 51.673668,
        lng: 39.182042,
        type: "recycling",
        district: "Ленинский",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, ПЭТ, стекло",
        contacts: "+7 (4732) 21-80-70",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass"]
    },
    {
        id: 136,
        name: "Воронежвторма (Ф. Энгельса)",
        address: "ул. Ф. Энгельса, двор д.64 (Центральный рынок), Воронеж",
        lat: 51.663646,
        lng: 39.194798,
        type: "recycling",
        district: "Ленинский",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, ПЭТ, стекло",
        contacts: "+7 (4732) 21-80-70",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass"]
    },
    {
        id: 137,
        name: "Воронежвторма (Колесниченко)",
        address: "ул. Колесниченко, 67, Воронеж",
        lat: 51.648745,
        lng: 39.163483,
        type: "recycling",
        district: "Ленинский",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, ПЭТ, стекло",
        contacts: "+7 (4732) 21-80-70",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass"]
    },
    {
        id: 138,
        name: "Воронежвторма (Хользунова, 105-А)",
        address: "ул. Хользунова, 105-А (Птичий рынок), Воронеж",
        lat: 51.700536,
        lng: 39.163402,
        type: "recycling",
        district: "Коминтерновский",
        hours: "Пн–Сб 08:00–17:00",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, ПЭТ, стекло",
        contacts: "+7 (4732) 21-80-70",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass"]
    },
    {
        id: 139,
        name: "Воронежвторма (Хользунова, 40-Е)",
        address: "ул. Хользунова, 40-Е, Воронеж",
        lat: 51.705459,
        lng: 39.191564,
        type: "recycling",
        district: "Коминтерновский",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, ПЭТ, стекло",
        contacts: "+7 (4732) 21-80-70",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass"]
    },
    {
        id: 140,
        name: "Воронежвторма (Лизюкова, 56-Г)",
        address: "ул. Лизюкова, 56-Г (во дворе), Воронеж",
        lat: 51.706106,
        lng: 39.151221,
        type: "recycling",
        district: "Коминтерновский",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, ПЭТ, стекло",
        contacts: "+7 (4732) 21-80-70",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass"]
    },
    {
        id: 141,
        name: "Воронежвторма (Лизюкова, 4-А)",
        address: "ул. Лизюкова, 4-А (за к/т «Мир»), Воронеж",
        lat: 51.707552,
        lng: 39.171532,
        type: "recycling",
        district: "Коминтерновский",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, ПЭТ, стекло",
        contacts: "+7 (4732) 21-80-70",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass"]
    },
    {
        id: 142,
        name: "Воронежвторма (9 Января, 136)",
        address: "ул. 9 Января, 136 (во дворе), Воронеж",
        lat: 51.673120,
        lng: 39.153009,
        type: "recycling",
        district: "Коминтерновский",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, ПЭТ, стекло",
        contacts: "+7 (4732) 21-80-70",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass"]
    },
    {
        id: 143,
        name: "Воронежвторма (Владимира Невского, 55)",
        address: "ул. Владимира Невского, 55 (во дворе), Воронеж",
        lat: 51.719148,
        lng: 39.174209,
        type: "recycling",
        district: "Коминтерновский",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, ПЭТ, стекло",
        contacts: "+7 (4732) 21-80-70",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass"]
    },
    {
        id: 144,
        name: "Воронежвторма (наб. Авиастроителей, 22)",
        address: "наб. Авиастроителей, 22 (ост. П. Осипенко), Воронеж",
        lat: 51.642977,
        lng: 39.234234,
        type: "recycling",
        district: "Железнодорожный",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, ПЭТ, стекло",
        contacts: "+7 (4732) 21-80-70",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass"]
    },
    {
        id: 145,
        name: "Воронежвторма (Димитрова, 90)",
        address: "ул. Димитрова, 90 (ост. «Рембаза»), Воронеж",
        lat: 51.668132,
        lng: 39.261750,
        type: "recycling",
        district: "Железнодорожный",
        hours: "Пн–Сб 09:00–17:00, Вс 09:00–14:00",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, ПЭТ, стекло",
        contacts: "+7 (952) 556-76-81",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass"]
    },
    {
        id: 146,
        name: "Воронежвторма (Ростовская, 2)",
        address: "ул. Ростовская, 2 (авторынок), Воронеж",
        lat: 51.622069,
        lng: 39.249838,
        type: "recycling",
        district: "Левобережный",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, ПЭТ, стекло",
        contacts: "+7 (4732) 21-80-70",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass"]
    },
    {
        id: 147,
        name: "Воронежвторма (25 Января, 6-В)",
        address: "ул. 25 Января, 6-В (ост. ДК «Электроника»), Воронеж",
        lat: 51.691732,
        lng: 39.255102,
        type: "recycling",
        district: "Железнодорожный",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, ПЭТ, стекло",
        contacts: "+7 (4732) 21-80-70",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass"]
    },
    {
        id: 148,
        name: "Воронежвторма (Ленинский пр-т, 186-В)",
        address: "Ленинский пр-т, 186-В (ост. «Суворова»), Воронеж",
        lat: 51.708199,
        lng: 39.277363,
        type: "recycling",
        district: "Железнодорожный",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, ПЭТ, стекло",
        contacts: "+7 (4732) 21-80-70",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass"]
    },
    {
        id: 149,
        name: "Седьмой лепесток (Южно-Моравская)",
        address: "ул. Южно-Моравская, 21А, Воронеж",
        lat: 51.654310,
        lng: 39.107976,
        type: "recycling",
        district: "Советский",
        hours: "Вт–Сб 08:30–16:30, перерыв 12:00–12:30",
        hoursType: "regular",
        description: "Макулатура, ПЭТ, пленка, стекло, металл, батарейки, электроника, блистеры, картон",
        contacts: "+7 (960) 135-17-00",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass", "metal", "battery", "electronics"]
    },
    {
        id: 150,
        name: "Седьмой лепесток (Беговая)",
        address: "ул. Беговая, 158, Воронеж",
        lat: 51.697678,
        lng: 39.141528,
        type: "recycling",
        district: "Коминтерновский",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, ПЭТ, пленка, стекло, батарейки",
        contacts: "+7 (960) 135-17-00",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass", "battery"]
    },
    {
        id: 151,
        name: "Седьмой лепесток (9 Января, 274)",
        address: "ул. 9 Января, 274, Воронеж",
        lat: 51.682927,
        lng: 39.124532,
        type: "recycling",
        district: "Коминтерновский",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, ПЭТ, пленка, стекло, батарейки",
        contacts: "+7 (960) 135-17-00",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass", "battery"]
    },
    {
        id: 152,
        name: "Седьмой лепесток (Моисеева, 65)",
        address: "ул. Моисеева, 65, Воронеж",
        lat: 51.649393,
        lng: 39.174910,
        type: "recycling",
        district: "Ленинский",
        hours: "Вт–Сб 08:30–16:40, перерыв 12:00–12:40",
        hoursType: "regular",
        description: "Макулатура, ПЭТ, пленка, стекло, металл, батарейки",
        contacts: "+7 (960) 135-17-00",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass", "metal", "battery"]
    },
    {
        id: 153,
        name: "Седьмой лепесток (Старых Большевиков, 92)",
        address: "ул. Старых Большевиков, 92, Воронеж",
        lat: 51.670104,
        lng: 39.247449,
        type: "recycling",
        district: "Железнодорожный",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, ПЭТ, пленка, стекло, батарейки",
        contacts: "+7 (960) 135-17-00",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass", "battery"]
    },
    {
        id: 154,
        name: "Седьмой лепесток (Переверткина, 27)",
        address: "ул. Переверткина, 27, Воронеж",
        lat: 51.691101,
        lng: 39.258067,
        type: "recycling",
        district: "Железнодорожный",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, ПЭТ, пленка, стекло, батарейки",
        contacts: "+7 (960) 135-17-00",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass", "battery"]
    },
    {
        id: 155,
        name: "Седьмой лепесток (Ворошилова, 24г)",
        address: "ул. Ворошилова, 24г, Воронеж",
        lat: 51.650209,
        lng: 39.162684,
        type: "recycling",
        district: "Коминтерновский",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, ПЭТ, пленка, стекло, батарейки",
        contacts: "+7 (960) 135-17-00",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass", "battery"]
    },
    {
        id: 156,
        name: "Седьмой лепесток (60 Армии, 22а)",
        address: "ул. 60 Армии, 22а, Воронеж",
        lat: 51.713662,
        lng: 39.160339,
        type: "recycling",
        district: "Коминтерновский",
        hours: "Вт–Сб 08:30–16:40, перерыв 12:00–12:40; Пн, Вс выходной",
        hoursType: "regular",
        description: "Макулатура, ПЭТ, пленка, стекло, металл, батарейки, электроника",
        contacts: "+7 (960) 135-17-00",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass", "metal", "battery", "electronics"]
    },
    {
        id: 157,
        name: "Седьмой лепесток (Владимира Невского, 15)",
        address: "ул. Владимира Невского, 15, Воронеж",
        lat: 51.708740,
        lng: 39.148382,
        type: "recycling",
        district: "Коминтерновский",
        hours: "Временно закрыт",
        hoursType: "regular",
        description: "Вторсырьё",
        contacts: "+7 (960) 135-17-00",
        website: "",
        recyclingTypes: []
    },
    {
        id: 158,
        name: "Вторсырье-Плюс",
        address: "Гаражный тупик, 1А, Воронеж",
        lat: 51.641820,
        lng: 39.280794,
        type: "recycling",
        district: "Железнодорожный",
        hours: "Пн–Пт 07:00–15:00",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, металлолом",
        contacts: "+7 (920) 454-66-36",
        website: "http://ooovts.com/",
        recyclingTypes: ["paper", "plastic", "metal"]
    },
    {
        id: 159,
        name: "Картон Черноземье",
        address: "ул. Транспортная, 1е, Воронеж",
        lat: 51.682061,
        lng: 39.213537,
        type: "recycling",
        district: "Центральный",
        hours: "Пн–Пт 09:00–18:00 (перерыв 13:00–14:00)",
        hoursType: "regular",
        description: "Макулатура, картон",
        contacts: "+7 (473) 246-76-67",
        website: "",
        recyclingTypes: ["paper"]
    },
    {
        id: 160,
        name: "Киво-Маркет",
        address: "ул. Екатерины Зеленко, 20, Воронеж",
        lat: 51.701909,
        lng: 39.105218,
        type: "recycling",
        district: "Коминтерновский",
        hours: "Пн–Пт 08:00–17:00, Сб 08:00–14:00",
        hoursType: "regular",
        description: "Макулатура, полиэтилен, вторсырьё",
        contacts: "(473) 279-00-60",
        website: "kivomarket.ru",
        recyclingTypes: ["paper", "plastic"]
    },
    {
        id: 161,
        name: "Разноинторг",
        address: "ул. Ростовская, 56, Воронеж",
        lat: 51.605045,
        lng: 39.240999,
        type: "recycling",
        district: "Левобережный",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, полиэтилен",
        contacts: "8-900-963-83-25",
        website: "",
        recyclingTypes: ["paper", "plastic"]
    },
    {
        id: 162,
        name: "Воронеж Картон",
        address: "ул. Ростовская, 45, помещение 1, Воронеж",
        lat: 51.602763,
        lng: 39.251329,
        type: "recycling",
        district: "Левобережный",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, картон, полиэтилен",
        contacts: "244-54-89",
        website: "",
        recyclingTypes: ["paper", "plastic"]
    },
    {
        id: 163,
        name: "ЭкоСити",
        address: "ул. Ломоносова, 98Б, Воронеж",
        lat: 51.715855,
        lng: 39.228153,
        type: "recycling",
        district: "Коминтерновский",
        hours: "по телефону",
        hoursType: "regular",
        description: "Макулатура, полиэтилен",
        contacts: "8-919-249-99-98",
        website: "",
        recyclingTypes: ["paper", "plastic"]
    },
    {
        id: 164,
        name: "Арго-ЭК",
        address: "пер. Электронный, 17, офис 10, Воронеж",
        lat: 51.664395,
        lng: 39.177659,
        type: "recycling",
        district: "Ленинский",
        hours: "по телефону",
        hoursType: "regular",
        description: "ПЭТ-бутылки",
        contacts: "(473) 278-41-66",
        website: "",
        recyclingTypes: ["plastic"]
    },
    {
        id: 165,
        name: "Славянское Наследие",
        address: "ул. Ростовская, 78, офис 82, Воронеж",
        lat: 51.592648,
        lng: 39.242840,
        type: "recycling",
        district: "Левобережный",
        hours: "по телефону",
        hoursType: "regular",
        description: "ПЭТ-бутылки",
        contacts: "8-920-222-00-22",
        website: "",
        recyclingTypes: ["plastic"]
    },
    {
        id: 166,
        name: "Эко-Парк",
        address: "ул. Холмистая, 56, корпус Б, Воронеж",
        lat: 51.668903,
        lng: 39.129644,
        type: "recycling",
        district: "Центральный",
        hours: "по телефону",
        hoursType: "regular",
        description: "Вторсырьё",
        contacts: "228-53-54",
        website: "",
        recyclingTypes: []
    },
    {
        id: 167,
        name: "М.Видео (Галерея Чижова)",
        address: "ул. Кольцовская, 35А (Галерея Чижова), Воронеж",
        lat: 51.667194,
        lng: 39.191906,
        type: "recycling",
        district: "Ленинский",
        hours: "Ежедневно 10:00–22:00",
        hoursType: "regular",
        description: "Батарейки, старая техника",
        contacts: "",
        website: "",
        recyclingTypes: ["battery", "electronics"]
    },
    {
        id: 168,
        name: "Мегаполисресурс",
        address: "ул. Кольцовская, 46, 1 этаж, Воронеж",
        lat: 51.669517,
        lng: 39.192678,
        type: "recycling",
        district: "Ленинский",
        hours: "Круглосуточно (перерыв 01:45–02:00)",
        hoursType: "24h",
        description: "Батарейки",
        contacts: "8-800-100-03-26",
        website: "",
        recyclingTypes: ["battery"]
    },
    {
        id: 169,
        name: "36 Колес",
        address: "пр-т Патриотов, 65З, Воронеж",
        lat: 51.639400,
        lng: 39.105802,
        type: "recycling",
        district: "Левобережный",
        hours: "Пн–Пт 07:00–20:00, Сб 10:00–15:00",
        hoursType: "regular",
        description: "Батарейки, старая техника",
        contacts: "",
        website: "",
        recyclingTypes: ["battery", "electronics"]
    },
    {
        id: 170,
        name: "ЭкоЛайнер",
        address: "ул. Балашовская, 29Е, Воронеж",
        lat: 51.595675,
        lng: 39.229958,
        type: "recycling",
        district: "Левобережный",
        hours: "Пн–Пт 08:00–17:00",
        hoursType: "regular",
        description: "Макулатура, пластик, стекло, металл",
        contacts: "",
        website: "",
        recyclingTypes: ["paper", "plastic", "glass", "metal"]
    },
    {
        id: 171,
        name: "Втормет",
        address: "ул. Дорожная, 17, Воронеж",
        lat: 51.662373,
        lng: 39.134836,
        type: "recycling",
        district: "Левобережный",
        hours: "Пн–Сб 08:00–18:00",
        hoursType: "regular",
        description: "Автомобильные аккумуляторы",
        contacts: "",
        website: "",
        recyclingTypes: ["battery"]
    },
    {
        id: 172,
        name: "Хетек Воронеж",
        address: "Монтажный пр-т, 5Е, Воронеж",
        lat: 51.636751,
        lng: 39.287127,
        type: "recycling",
        district: "Железнодорожный",
        hours: "Ежедневно 08:00–20:00",
        hoursType: "regular",
        description: "Автомобильные аккумуляторы",
        contacts: "",
        website: "",
        recyclingTypes: ["battery"]
    },
    {
        id: 173,
        name: "Эколан (старый город)",
        address: "ул. 9 Января, 55, Воронеж",
        lat: 51.664378,
        lng: 39.181216,
        type: "recycling",
        district: "Советский",
        hours: "нет графика",
        hoursType: "regular",
        description: "Макулатура, пластик, батарейки",
        contacts: "",
        website: "",
        recyclingTypes: ["paper", "plastic", "battery"]
    },
    {
        id: 174,
        name: "ПЭТ-Пласт",
        address: "ул. 9 Января, 55, Воронеж",
        lat: 51.664378,
        lng: 39.181216,
        type: "recycling",
        district: "Советский",
        hours: "по телефону",
        hoursType: "regular",
        description: "Пластиковые бутылки, вторсырьё",
        contacts: "",
        website: "",
        recyclingTypes: ["plastic"]
    },
    {
        id: 175,
        name: "Акрон Скрап (Пирогова)",
        address: "ул. Пирогова, 87/5, Воронеж",
        lat: 51.658926,
        lng: 39.161633,
        type: "recycling",
        district: "Левобережный",
        hours: "Пн–Пт 08:00–18:00, Сб 08:00–15:00",
        hoursType: "regular",
        description: "Черный и цветной металлолом, макулатура, вторсырьё",
        contacts: "8 (800) 555-44-43",
        website: "",
        recyclingTypes: ["metal", "paper"]
    },
    {
        id: 176,
        name: "Акрон Скрап (Витрука)",
        address: "ул. Витрука, 3, Воронеж",
        lat: 51.703461,
        lng: 39.279114,
        type: "recycling",
        district: "Коминтерновский",
        hours: "Ежедневно 08:30–19:00",
        hoursType: "regular",
        description: "Металлолом",
        contacts: "",
        website: "",
        recyclingTypes: ["metal"]
    },
    {
        id: 177,
        name: "Акрон Скрап (Выборгская)",
        address: "ул. Выборгская, 37, Воронеж",
        lat: 51.638662,
        lng: 39.209360,
        type: "recycling",
        district: "Левобережный",
        hours: "Пн–Пт 08:00–18:00, Сб 08:00–15:00",
        hoursType: "regular",
        description: "Черный и цветной металлолом, макулатура, вторсырьё",
        contacts: "8 (800) 555-44-43",
        website: "",
        recyclingTypes: ["metal", "paper"]
    },
    {
        id: 178,
        name: "Акрон Скрап (Ленинский пр-т)",
        address: "Ленинский пр-т, 174/5, Воронеж",
        lat: 51.700474,
        lng: 39.274578,
        type: "recycling",
        district: "Железнодорожный",
        hours: "Пн–Пт 08:00–18:00, Сб 08:00–15:00",
        hoursType: "regular",
        description: "Черный и цветной металлолом, автомобили, аккумуляторы, электроника",
        contacts: "8 (800) 555-44-43",
        website: "",
        recyclingTypes: ["metal", "battery", "electronics"]
    },
    {
        id: 179,
        name: "Акрон Скрап (Майская)",
        address: "Майская ул., 10И, Воронеж",
        lat: 51.582083,
        lng: 39.317823,
        type: "recycling",
        district: "Коминтерновский",
        hours: "Пн–Сб 08:00–18:00",
        hoursType: "regular",
        description: "Металлолом, вторсырьё",
        contacts: "",
        website: "",
        recyclingTypes: ["metal"]
    },
    {
        id: 180,
        name: "Крышка-малышка (парк Арена)",
        address: "парк Арена, Воронеж",
        lat: 51.708191,
        lng: 39.160633,
        type: "recycling",
        district: "Коминтерновский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Крышки",
        contacts: "",
        website: "",
        recyclingTypes: ["plastic"]
    },
    {
        id: 181,
        name: "Крышка-малышка (парк Дельфин)",
        address: "парк Дельфин, Воронеж",
        lat: 51.686531,
        lng: 39.253308,
        type: "recycling",
        district: "Ленинский",
        hours: "Круглосуточно",
        hoursType: "24h",
        description: "Крышки",
        contacts: "",
        website: "",
        recyclingTypes: ["plastic"]
    },

































        // ========== СЕКОНД-ХЕНДЫ (id 182–188) ==========
    {
        id: 182,
        name: "Эко-секонд-хенд",
        address: "ул. Минская, 63А, Воронеж",
        lat: 51.690292,
        lng: 39.280022,
        type: "secondhand",
        district: "Железнодорожный",
        hours: "Чт–Вс 11:00–19:00, Пн–Ср выходной",
        hoursType: "regular",
        description: "Центр осознанного потребления, эко-секонд-хенд, пункт приёма вторсырья",
        contacts: "+7 (952) 953-05-44",
        website: "",
        recyclingTypes: []
    },
    {
        id: 183,
        name: "Бутик Добра",
        address: "ул. Карла Маркса, 116А (1 этаж), Воронеж",
        lat: 51.674595,
        lng: 39.194170,
        type: "secondhand",
        district: "Ленинский",
        hours: "Пн–Чт 11:00–19:00, Пт 11:00–15:00, Сб–Вс выходной",
        hoursType: "regular",
        description: "Благотворительный магазин (секонд-хенд)",
        contacts: "+7 (473) 213-34-75, +7 (919) 236-82-21",
        website: "",
        recyclingTypes: []
    },
    {
        id: 184,
        name: "Секонд-хенд",
        address: "ул. Моисеева, 42 (1 этаж), Воронеж",
        lat: 51.651416,
        lng: 39.177263,
        type: "secondhand",
        district: "Ленинский",
        hours: "Пн–Пт 10:00–19:00, Сб 10:00–18:00, Вс 09:00–16:00",
        hoursType: "regular",
        description: "Секонд-хенд",
        contacts: "+7 (968) 190-06-66",
        website: "",
        recyclingTypes: []
    },
    {
        id: 185,
        name: "Секонд-хенд Микс",
        address: "ул. Пушкинская, 4 (цокольный этаж), Воронеж",
        lat: 51.663870,
        lng: 39.202111,
        type: "secondhand",
        district: "Центральный",
        hours: "не указан",
        hoursType: "regular",
        description: "Секонд-хенд",
        contacts: "+7 (905) 644-87-13",
        website: "",
        recyclingTypes: []
    },
    {
        id: 186,
        name: "Планета Секонд-Хенд",
        address: "ул. Кольцовская, 41, Воронеж",
        lat: 51.663088,
        lng: 39.188825,
        type: "secondhand",
        district: "Ленинский",
        hours: "не указан",
        hoursType: "regular",
        description: "Секонд-хенд",
        contacts: "",
        website: "",
        recyclingTypes: []
    },
    {
        id: 187,
        name: "Секонд-хенд",
        address: "ул. Федора Тютчева, 95е, Воронеж",
        lat: 51.739492,
        lng: 39.311561,
        type: "secondhand",
        district: "Коминтерновский",
        hours: "не указан",
        hoursType: "regular",
        description: "Секонд-хенд",
        contacts: "",
        website: "",
        recyclingTypes: []
    }
    // {
    //     id: 188,
    //     name: "Всячина",
    //     address: "ул. Волго-Донская, 4, Воронеж",
    //     lat: 51.614296,
    //     lng: 39.248796,
    //     type: "shop",  // было "secondhand"
    //     district: "Левобережный",
    //     hours: "Пн–Пт 11:00–19:00, Сб–Вс 10:00–16:00",
    //     hoursType: "regular",
    //     description: "Благотворительный магазин / секонд-хенд",
    //     contacts: "+7 (951) 855-10-16",
    //     website: "",
    //     recyclingTypes: []
    // }
];

const typeColors = {
    water: "#1E90FF",
    recycling: "#2E8B57",
    event: "#FF8C00",
    secondhand: "#9B59B6",
    shop: "#E67E22"   // оранжевый для магазинов
};